import Link from "next/link";
import { Logo } from "@/components/ui/logo";

export const metadata = {
  title: "Terms of Service | LandlordComply",
  description: "Terms of Service for LandlordComply - Security deposit compliance software",
};

export default function TermsPage() {
  const lastUpdated = "January 2025";

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="mx-auto max-w-4xl px-4 py-4">
          <Link href="/" className="inline-flex items-center gap-2">
            <Logo iconSize={32} showCheckmark={false} />
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-4xl px-4 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {lastUpdated}</p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using LandlordComply ("Service"), you agree to be bound by these Terms of Service ("Terms").
              If you do not agree to these Terms, you may not use the Service. We reserve the right to modify these Terms
              at any time, and your continued use of the Service constitutes acceptance of any modifications.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              LandlordComply is an educational software tool designed to help landlords and property managers understand
              security deposit regulations and generate compliance documentation. The Service provides jurisdiction-specific
              information, deadline calculations, document generation, and record-keeping features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">3. Important Disclaimer: Not Legal Advice</h2>
            <div className="bg-warning/10 border border-warning/30 rounded-lg p-4 mb-4">
              <p className="text-foreground font-medium">
                LandlordComply is an educational tool only and does not provide legal advice. The information and
                documents generated by this Service are for informational purposes only and should not be construed
                as legal advice or a substitute for consultation with a qualified attorney.
              </p>
            </div>
            <p className="text-muted-foreground leading-relaxed">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-2 text-muted-foreground">
              <li>Laws and regulations change frequently, and while we strive to maintain accurate information, we cannot guarantee that all information is current or complete.</li>
              <li>The Service does not create an attorney-client relationship between you and LandlordComply or any of its affiliates.</li>
              <li>You should always verify information with official government sources and consult a licensed attorney in your jurisdiction for specific legal questions.</li>
              <li>You are solely responsible for ensuring compliance with all applicable laws and regulations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">4. User Accounts</h2>
            <p className="text-muted-foreground leading-relaxed">
              To use certain features of the Service, you must create an account. You agree to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-2 text-muted-foreground">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain the security of your password and account</li>
              <li>Accept responsibility for all activities that occur under your account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">5. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-2 text-muted-foreground">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the rights of others</li>
              <li>Submit false or misleading information</li>
              <li>Attempt to gain unauthorized access to the Service or its systems</li>
              <li>Use the Service for any fraudulent or unlawful purpose</li>
              <li>Resell or redistribute the Service without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">6. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service and its original content, features, and functionality are owned by LandlordComply and are
              protected by international copyright, trademark, and other intellectual property laws. You retain
              ownership of any data you submit to the Service, but grant us a license to use it to provide the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">7. Payment and Subscriptions</h2>
            <p className="text-muted-foreground leading-relaxed">
              Certain features of the Service require payment. By purchasing a subscription or one-time product, you agree to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-2 text-muted-foreground">
              <li>Pay all fees associated with your selected plan</li>
              <li>Provide accurate billing information</li>
              <li>Accept that subscriptions will automatically renew unless cancelled</li>
              <li>Understand that refunds are handled on a case-by-case basis</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">8. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, LandlordComply shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages, including but not limited to loss of profits, data, or other
              intangible losses, resulting from:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-2 text-muted-foreground">
              <li>Your use or inability to use the Service</li>
              <li>Any errors, inaccuracies, or omissions in the content provided</li>
              <li>Unauthorized access to or alteration of your data</li>
              <li>Any legal penalties, fines, or damages arising from your reliance on the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">9. Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to indemnify and hold harmless LandlordComply and its officers, directors, employees, and agents
              from any claims, damages, losses, or expenses (including reasonable attorney fees) arising from your use
              of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">10. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may terminate or suspend your account and access to the Service immediately, without prior notice,
              for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
              Upon termination, your right to use the Service will cease immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">11. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware,
              without regard to its conflict of law provisions. Any disputes arising from these Terms or the Service
              shall be resolved in the courts of Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-4">12. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms, please contact us at:{" "}
              <a href="mailto:support@landlordcomply.com" className="text-primary hover:underline">
                support@landlordcomply.com
              </a>
            </p>
          </section>
        </div>

        {/* Back Link */}
        <div className="mt-12 pt-8 border-t border-border">
          <Link href="/" className="text-primary hover:underline text-sm">
            &larr; Back to Home
          </Link>
        </div>
      </main>
    </div>
  );
}
